---

- name: "Add nodes for group: {{ group.name }}"
  add_host:
    name: "{{ node.name }}"
    groups:
      - cluster
      - "{{ group.name }}"
    ansible_host: "{{ node.ip }}"
    ansible_user: "{{ cluster_deploy_user | default('root') }}"
    ansible_ssh_private_key_file: "{{ cluster_private_key_file }}"
  with_items: "{{ group.nodes }}"
  loop_control:
    loop_var: node
