---
- name: Wait for access to SSH port on nodes
  local_action:
    module: wait_for
    host: "{{ hostvars[host].ansible_host }}"
    port: 22
    state: started
    timeout: 600
  when: 
    - cluster_gw_group is not defined or host in groups[cluster_gw_group]

- name: Scan for SSH keys
  command: ssh-keyscan {{ hostvars[host].ansible_host }}
  register: keyscan_result
  changed_when: False

- name: Ensure servers are in SSH known hosts
  blockinfile:
    block: |
      {% for key in keyscan_result.stdout_lines %}
      {{ key }}
      {% endfor %}
    create: true
    marker: "# {mark} P3-APPLIANCES MANAGED BLOCK FOR {{ cluster_name }}.{{ host }}"
    path: "~/.ssh/known_hosts"

- name: "Wait for {{ host }} to become available"
  ping:
  delegate_to: "{{ host }}"
  register: host_available
  until: host_available is succeeded
  retries: 60
  delay: 5
