---

parameters:
  # This is the ID of the current CentOS 7 image on JASMIN
  cluster_image: d7df64a3-9b2e-4ff2-820f-4481671d1dcf


resource_registry:
  "Cluster::Node": "./resources/node.yaml"
  "Cluster::NodeWithVolume": "./resources/node-with-volume.yaml"
  "Cluster::Group": "./resources/group.yaml"
