---
heat_template_version: 2016-04-08

description: >
  Heat stack template for a stack containing one Neutron port which is on 
  a named network and subnet (and does not have a floating IP)

parameters:
  node_idx:
    type: number
    label: Node index within cluster group
  cluster_network:
    type: string
    label: Network to which the nodes should be attached
    constraints:
      - custom_constraint: neutron.network
  cluster_fips:
    type: json
    label: List of UUIDs of prealloacted floating IPs
    default: []

resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: cluster_network }

outputs:
  OS::stack_id:
    description: The network list
    value: 
      - port: { get_resource: port }

  networks:
    description: The network list
    value: 
      - port: { get_resource: port }

  primary_port: 
    description: Network port resources for the primary port as a scalar
    value: { get_resource: port }

  primary_ip:
    description: ID of the IP assigned on the named cluster network
    value: { get_attr: [ port, fixed_ips, 0, ip_address ] }
